export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENTS = 'DELETE_COMMENTS';

export const DISMISS_EDITABLE_COMMENT = 'DISMISS_EDITABLE_COMMENT';
export const DISMISS_EDITABLE_POST = 'DISMISS_EDITABLE_POST';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const SORT_BY_VOTE = 'SORT_BY_VOTE';
export const SORT_BY_DATE = 'SORT_BY_DATE';